dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: spring-boot-gke
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: demo1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: gomatstest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: timeawesome-golang
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
